### ISSUE TITLE
Android api14-18

### ISSUE THREAD

**Issue by laka2012** [Unic8/controller-lib#2]
Hi, when I use your lib in api14-18, I get one fatal error, there is no error for api21+, could you help me? Thank you very much.

My layout:
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical" >

    <com.jin.game.littlesufgame.LittleSurfaceView
        android:id="@+id/surfaceView"
        android:layout_width="fill_parent"
        android:layout_height="fill_parent"
        android:layout_alignParentBottom="true" />

    <com.andretietz.android.controller.DirectionView
        android:id="@+id/viewDirection"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"/>

    <com.andretietz.android.controller.ActionView
        android:id="@+id/viewAction"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true" />

</RelativeLayout>`

Fatal Error:
`FATAL EXCEPTION: main
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jin.game.littlesufgame/com.jin.game.littlesufgame.MainActivity}: android.view.InflateException: Binary XML file line #14: Error inflating class com.andretietz.android.controller.DirectionView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2355)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391)
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:151)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                at android.os.Looper.loop(Looper.java:155)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5520)
                                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
                                                                                at dalvik.system.NativeStart.main(Native Method)
                                                                             Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class com.andretietz.android.controller.DirectionView
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:613)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                at com.jin.game.littlesufgame.MainActivity.onCreate(MainActivity.java:56)
                                                                                at android.app.Activity.performCreate(Activity.java:5066)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                at android.os.Looper.loop(Looper.java:155) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5520) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: java.lang.reflect.InvocationTargetException
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at com.jin.game.littlesufgame.MainActivity.onCreate(MainActivity.java:56) 
                                                                                at android.app.Activity.performCreate(Activity.java:5066) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                at android.os.Looper.loop(Looper.java:155) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5520) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: android.content.res.Resources$NotFoundException: File res/drawable/direction_background.xml from drawable resource ID #0x7f020057
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:1953)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:667)
                                                                                at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
                                                                                at com.andretietz.android.controller.InputView.init(InputView.java:149)
                                                                                at com.andretietz.android.controller.DirectionView.init(DirectionView.java:65)
                                                                                at com.andretietz.android.controller.DirectionView.<init>(DirectionView.java:49)
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at com.jin.game.littlesufgame.MainActivity.onCreate(MainActivity.java:56) 
                                                                                at android.app.Activity.performCreate(Activity.java:5066) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                at android.os.Looper.loop(Looper.java:155) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5520) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
                                                                             Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
                                                                                at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:877)
                                                                                at android.graphics.drawable.Drawable.createFromXml(Drawable.java:818)
                                                                                at android.content.res.Resources.loadDrawable(Resources.java:1950)
                                                                                at android.content.res.Resources.getDrawable(Resources.java:667) 
                                                                                at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374) 
                                                                                at com.andretietz.android.controller.InputView.init(InputView.java:149) 
                                                                                at com.andretietz.android.controller.DirectionView.init(DirectionView.java:65) 
                                                                                at com.andretietz.android.controller.DirectionView.<init>(DirectionView.java:49) 
                                                                                at java.lang.reflect.Constructor.constructNative(Native Method) 
                                                                                at java.lang.reflect.Constructor.newInstance(Constructor.java:417) 
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:587) 
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:746) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:489) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:352) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at com.jin.game.littlesufgame.MainActivity.onCreate(MainActivity.java:56) 
                                                                                at android.app.Activity.performCreate(Activity.java:5066) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1101) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2391) 
                                                                                at android.app.ActivityThread.access$600(ActivityThread.java:151) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1335) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                at android.os.Looper.loop(Looper.java:155) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5520) 
                                                                                at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796) 
                                                                                at dalvik.system.NativeStart.main(Native Method) 
`

**Comment by andretietz** [comment]
This is propably related to the creation of the vector drawables.

Instead of ContextCompat I should use VectorDrawableCompat. I will fix this as soon as I can. Hopefully before the weekend

**Comment by andretietz** [comment]
Could you do this and create a PR for it? In that way you can immediately test if this solves your issue.

It's here:
https://github.com/andretietz/controller-lib/search?utf8=%E2%9C%93&q=ContextCompat&type=

**Comment by laka2012** [comment]
|o|,,,it works now! You are right, I use 
`Drawable backgroundDrawable = VectorDrawableCompat.create(getResources(), background, null);`

But also need this in activity
`static {
    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}`
or this way `Drawable drawable = AppCompatResources.getDrawable(mContext, mImageTitleResId);`
I have not tried this

Do you want me to commit and review by you?

**Comment by JohanJarvi** [comment]
Hey @andretietz could you please push the fixes? I can't figure out how to use the library without simply using it as a dependency and I can't get it running on my API18 Note 2. Thanks!

**Comment by andretietz** [comment]
Sorry for taking so long. Issue fixed, new version released
